spring.jpa.database: "HSQL"
spring.datasource.platform:  "hsql"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "org.hsqldb.jdbc.JDBCDriver"
spring.datasource.url: "jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1"
spring.datasource.username: "sa"
spring.datasource.password:
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.HSQLDialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
#spring.jpa.database: "POSTGRESQL"
#spring.datasource.platform:  "postgres"
#spring.database.driverClassName: "org.postgresql.Driver"
#spring.datasource.url: "jdbc:postgresql://database:5432/eagle_eye_dev"
#spring.datasource.username: "postgres_dev"
#spring.datasource.password: "{cipher}d495ce8603af958b2526967648aa9620b7e834c4eaff66014aa805450736e119"
#spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"